### ISSUE TITLE
Adapter activities do not show Output documents lists in Script tab

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw-studio#58]
For Script and Dynamic Java activities, a user has to select output documents as writable in order for MDW to apply the modified value (assigned/modified within the script/java code).  For Adapter type activities, pre and post scripts can be written but the Read-only/Writable output document lists are not displayed, so document type variables cannot be assigned/modified.   This would impact production only since for non-prod envs it will still perform the document variable update and just log a warning.

**Comment by naveena-bellamkonda** [comment]
changes made for [issue #617](https://github.com/CenturyLinkCloud/mdw/issues/617) fixed this.
