### ISSUE TITLE
Discovery errors on Windows

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw-studio#63]
```
2019-02-26 17:50:42,509 [ 374894]   WARN - w.studio.action.DiscoverAssets - https://api.github.com/repos/CenturyLinkCloud/mdw/git/trees/null?ref=6.1.15&recursive=true -> 404: Not Found
```
This is due to paths that contain backslashes (`\`) in GitDiscoverer.

```
java.nio.file.DirectoryNotEmptyException: F:\mdw-aprilia\assets\com\centurylink\mdw\emp
```
This is due to Java bug that prevents move across drives (i.e. moving from temp location on C: drive over to project on F: drive) - https://bugs.openjdk.java.net/browse/JDK-8020199

**Comment by jbrojdeCTL** [comment]
For resolving Java bug on Windows, we'll clone repo into a new temp location created on same drive as project.
