### ISSUE TITLE
Dynamic java/groovy script contents jump from one editor to another

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw-studio#68]
While having 2 editor tabs open for dynamic java and groovy script (different activities on same process definition), sometimes it has been observed that the content/code from one activity (editor) automatically replaces the content/code of the other activity (editor).   This was observed prior to, and also with Studio 1.2.1.

**Comment by donaldoakes** [comment]
Steps to reproduce:
  1. Launch IntelliJ fresh, and remove all breakpoints via Run > View Breakpoints.
  2. Open a process definition containing two dynamic Java activities.
  3. Open Java for both activities by right-clicking and selecting Open Java.
  4. Make changes to the Java source for both activities.
  5. Save the process without closing Java sources.
  6. Start the MDW server and set a breakpoint in the second activity's dynamic Java.
  7. Run the flow to hit the breakpoint, and make a change to the code without continuing.
  8. While stopped at the breakpoint, go back to the process and open the first Activity's Java.
  9. It will contain the source from the wrong activity.
