### ISSUE TITLE
Issue with dragging activity into embedded subflow

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw-studio#70]
An email notification activity can be dragged into the embedded sub-flow, but then cannot be moved or resized.  Transitions can be connected to it though.

**Comment by donaldoakes** [comment]
Can't reproduce.  Was this observed on 1.2.1?

**Comment by jbrojdeCTL** [comment]
Absolutely...perhaps is a Windows-only issue.

**Comment by donaldoakes** [comment]
Happens when main process has the highest activity id (subflow assigns duplicate id).  Same thing happens for transitions.
